language: python
cache: pip

python:
  - "3.6"

env:
  global:
    - OMP_NUM_THREADS=4
    - CUDA_VISIBLE_DEVICES=-1

install:
  - pip install cython
  - pip install -r .travis.requirements.txt

script:
  - flake8
  - test "$(autopep8 --recursive --diff .)" = ""
  - pylint --jobs=4 pytoolkit *.py
  - pytest
