language: python

python:
  - "3.6"

env:
  global:
    - OMP_NUM_THREADS=4
    - CUDA_VISIBLE_DEVICES=-1
    - PYTHONWARNINGS=default

install:
  - pip install -r .travis.requirements.txt

script:
  - pytest
