language: python
cache: pip

python:
  - "3.7"

env:
  global:
    - OMP_NUM_THREADS=4
    - CUDA_VISIBLE_DEVICES=-1

install:
  - pip install cython
  - pip install -r requirements.travis.txt

script:
  - black --check .
  - flake8
  - mypy pytoolkit scripts
  - pylint --jobs=4 pytoolkit scripts
  - env PYTOOLKIT_BACKEND=tf pytest
  - env PYTOOLKIT_BACKEND=keras pytest
