language: python
cache: pip

python:
  - "3.7"

env:
  global:
    - OMP_NUM_THREADS=4
    - CUDA_VISIBLE_DEVICES=-1

install:
  - sudo apt-get install graphviz
  - pip install cython
  - pip install -r requirements.travis.txt

script:
  - black --check .
  - flake8
  - mypy pytoolkit scripts tests
  - pylint --jobs=4 pytoolkit scripts
  - pytest
